version: 2

models:
  - name: dim_dates
    description: "Date dimension table with daily granularity for property transactions. Includes hierarchies for year, quarter, month, week, and day."
    columns:
      - name: date_id
        description: "Surrogate primary key in YYYYMMDD format."
        tests:
          - not_null
          - unique
      - name: full_date
        description: "Full calendar date."
        tests:
          - not_null
      - name: year
        description: "Year extracted from full_date."
      - name: quarter
        description: "Quarter extracted from full_date."
      - name: month
        description: "Month number (1-12)."
      - name: month_name
        description: "Month name."
      - name: day
        description: "Day of month."
      - name: day_of_week_num
        description: "Day of week as integer (1=Sunday)."
      - name: day_of_week_name
        description: "Name of the day of the week."
      - name: iso_week
        description: "ISO week string (YYYY-W##)."
      - name: year_week_id
        description: "Integer surrogate key combining year and week (YYYYWW)."
