version: 2

models:
  - name: dim_dates
    description: "Date dimension table with daily granularity for property transactions. Includes hierarchies for year, quarter, month, week, and day."
    columns:
      - name: date_id
        description: "Surrogate primary key in YYYYMMDD format."
        tests:
          - not_null
          - unique
      - name: full_date
        description: "Full calendar date."
        tests:
          - not_null
      - name: year
        description: "Year extracted from full_date."
      - name: quarter
        description: "Quarter extracted from full_date."
      - name: month
        description: "Month number (1-12)."
      - name: month_name
        description: "Month name."
      - name: day
        description: "Day of month."
      - name: day_of_week_num
        description: "Day of week as integer (1=Sunday)."
      - name: day_of_week_name
        description: "Name of the day of the week."
      - name: iso_week
        description: "ISO week string (YYYY-W##)."
      - name: year_week_id
        description: "Integer surrogate key combining year and week (YYYYWW)."

  
  - name: dim_location
    description: "Dimension table containing location details (postcode, suburb, LGA, GCCSA classification for NSW)."
    columns:
      - name: location_id
        description: "Surrogate primary key for location (hashed combination of postcode, suburb, lga_code)."
        tests:
          - not_null
          - unique

      - name: postcode
        description: "Postcode of the property (integer)."
        tests:
          - not_null
          - relationships:
              to: ref('stg_google_nswprop_data_2001_2024')
              field: postcode

      - name: suburb
        description: "Suburb name from the raw property data."
        tests:
          - not_null

      - name: lga_code
        description: "Local Government Area code for the property."
        tests:
          - not_null

      - name: gccsa_code
        description: "Greater Capital City Statistical Area code (Greater Sydney or Rest of NSW)."
        tests:
          - accepted_values:
              values: ['1GSYD', '1RNSW']
              quote: true

      - name: gccsa_name
        description: "Greater Capital City Statistical Area name (Greater Sydney or Rest of NSW)."
        tests:
          - accepted_values:
              values: ['Greater Sydney', 'Rest of NSW']
              quote: true